### ISSUE TITLE
config.py?

### ISSUE THREAD

**Issue by villain** [cleesmith/rulespy#1]
any chance an example config.py could be added at all?

**Comment by cleesmith** [comment]
thanks ... I added an example config.py file

**Comment by villain** [comment]
what do you have exported in the APP_SETTINGS variable?

when you try to run the 'python manage.py seeds', an error is raised:

KeyError: 'APP_SETTINGS'

that appears to be picked up from the os environment variables

**Comment by cleesmith** [comment]
It should match what's in config.py, for example:
```export APP_SETTINGS="config.DevelopmentConfig"```

I use:
Virtualenv – http://www.virtualenv.org/en/latest/
Virtualenvwrapper – http://virtualenvwrapper.readthedocs.org/en/latest/
to handle dependencies.

If you're new to virtual environments in python, this may help:
https://realpython.com/blog/python/flask-by-example-part-1-project-setup/
